# Generated by Django 4.0.5 on 2022-07-04 03:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('picture_1', models.ImageField(upload_to='products/')),
                ('picture_2', models.ImageField(blank=True, upload_to='products/')),
                ('picture_3', models.ImageField(blank=True, upload_to='products/')),
                ('picture_4', models.ImageField(blank=True, upload_to='products/')),
                ('picture_5', models.ImageField(blank=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=True)),
                ('features', multiselectfield.db.fields.MultiSelectField(choices=[('teen', 'teenagers'), ('adlt', 'adults'), ('boy', 'boys'), ('girl', 'girls'), ('man', 'mans'), ('wom', 'women'), ('sprt', 'sport'), ('csl', 'casual'), ('clth', 'clothes'), ('bg', 'bag'), ('shoe', 'shoe'), ('acsr', 'accessory')], max_length=53)),
            ],
        ),
    ]
