# Generated by Django 4.0.5 on 2022-07-04 07:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('teen', 'teenagers'), ('adlt', 'adults'), ('boy', 'boys'), ('girl', 'girls'), ('man', 'men'), ('wom', 'women'), ('sprt', 'sport'), ('csl', 'casual'), ('clth', 'clothes'), ('bg', 'bag'), ('shoe', 'shoe'), ('acsr', 'accessory')], max_length=53),
        ),
    ]
